server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://192.168.19.156:3306/frogsmoke
    username: root
    password: admin
---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080