server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://64.225.77.37:3306/shishasmataro?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: Camacho300*
application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 10
---
spring:
  config:
    activate:
      on-profile: docker
