server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mataro?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root

application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 10
---
spring:
  config:
    activate:
      on-profile: docker
